/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import com.formdev.flatlaf.FlatDarkLaf;
import java.io.FileWriter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ISAACOLIVEIRANUNES
 */
public class CardSus extends javax.swing.JFrame {
        private javax.swing.JTextArea listarCardSusArea;


    /**
     * Creates new form CardSus
     */
    public CardSus() {
        initComponents();
        setSize(493, 584);
        setTitle("Cartão SUS");
        setLocationRelativeTo(null);
        setResizable(false);

        salvarCardSusButton.setContentAreaFilled(false); // Remove o preenchimento de fundo (cor cinza)
        salvarCardSusButton.setBorderPainted(false);     // Remove a borda do botão
        salvarCardSusButton.setFocusPainted(false);      // (Opcional) Remove a linha de foco ao clicar
        salvarCardSusButton.setOpaque(false);

        voltarCardSusButton.setContentAreaFilled(false); // Remove o preenchimento de fundo (cor cinza)
        voltarCardSusButton.setBorderPainted(false);     // Remove a borda do botão
        voltarCardSusButton.setFocusPainted(false);      // (Opcional) Remove a linha de foco ao clicar
        voltarCardSusButton.setOpaque(false);

        jButton3.setContentAreaFilled(false); // Remove o preenchimento de fundo (cor cinza)
        jButton3.setBorderPainted(false);     // Remove a borda do botão
        jButton3.setFocusPainted(false);      // (Opcional) Remove a linha de foco ao clicar
        jButton3.setOpaque(false);

          cardSusTextArea.setText("");
        carregarCardSus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cardSusTextArea = new javax.swing.JTextArea();
        salvarCardSusButton = new javax.swing.JButton();
        voltarCardSusButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardSusTextArea.setColumns(20);
        cardSusTextArea.setRows(5);
        jScrollPane1.setViewportView(cardSusTextArea);

        salvarCardSusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/iconeDeSalvarNew.png"))); // NOI18N
        salvarCardSusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarCardSusButtonActionPerformed(evt);
            }
        });

        voltarCardSusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/iconeDeVoltarNew.png"))); // NOI18N
        voltarCardSusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCardSusButtonActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Icon/iconeDeInforManagerNew2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salvarCardSusButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarCardSusButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(voltarCardSusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarCardSusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarCardSusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCardSusButtonActionPerformed
        PosLogin pos = new PosLogin();
        pos.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_voltarCardSusButtonActionPerformed

    private void salvarCardSusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarCardSusButtonActionPerformed
      String cardSus = cardSusTextArea.getText().trim();

    if (cardSus.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Digite um Cartão do SUS!");
        return;
    }

    try {
        
        InfoDAO dao = new InfoDAO();
    dao.inserirCardSus(cardSus);

    FileWriter fw = new FileWriter("cartaoSus.txt", true);
    fw.write(cardSus + "\n");
    fw.close();

    JOptionPane.showMessageDialog(null, "Cartão do SUS salvo com sucesso!");
    cardSusTextArea.setText("");

} catch (Exception e) {
    JOptionPane.showMessageDialog(null,
            "Erro ao salvar:\n" + e.getMessage());
}
                       

    }//GEN-LAST:event_salvarCardSusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardSus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardSus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardSus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardSus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        FlatDarkLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardSus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cardSusTextArea;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salvarCardSusButton;
    private javax.swing.JButton voltarCardSusButton;
    // End of variables declaration//GEN-END:variables
private void carregarCardSus() {
    try {
        InfoDAO dao = new InfoDAO();
        List<String> cartaoSus = dao.listarCardSus();

        cardSusTextArea.setText("");

        for (String c : cartaoSus) {
            cardSusTextArea.append(c + "\n");
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}




}
