/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import com.formdev.flatlaf.FlatDarkLaf;
import java.io.FileWriter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ISAACOLIVEIRANUNES
 */
public class Cartao extends javax.swing.JFrame {
        private javax.swing.JTextArea listarCartaoArea;


    /**
     * Creates new form Cartao
     */
    public Cartao() {
        initComponents();
        setSize(493, 584);
        setTitle("Cartão");
        setLocationRelativeTo(null);
        setResizable(false);

        salvarCartaoButton.setContentAreaFilled(false); // Remove o preenchimento de fundo (cor cinza)
        salvarCartaoButton.setBorderPainted(false);     // Remove a borda do botão
        salvarCartaoButton.setFocusPainted(false);      // (Opcional) Remove a linha de foco ao clicar
        salvarCartaoButton.setOpaque(false);

        voltarCartaoButton.setContentAreaFilled(false); // Remove o preenchimento de fundo (cor cinza)
        voltarCartaoButton.setBorderPainted(false);     // Remove a borda do botão
        voltarCartaoButton.setFocusPainted(false);      // (Opcional) Remove a linha de foco ao clicar
        voltarCartaoButton.setOpaque(false);

        jButton3.setContentAreaFilled(false); // Remove o preenchimento de fundo (cor cinza)
        jButton3.setBorderPainted(false);     // Remove a borda do botão
        jButton3.setFocusPainted(false);      // (Opcional) Remove a linha de foco ao clicar
        jButton3.setOpaque(false);
        
        cartaoTextArea.setText("");
        carregarCartao();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartaoTextArea = new javax.swing.JTextArea();
        salvarCartaoButton = new javax.swing.JButton();
        voltarCartaoButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cartaoTextArea.setColumns(20);
        cartaoTextArea.setRows(5);
        jScrollPane1.setViewportView(cartaoTextArea);

        salvarCartaoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/iconeDeSalvarNew.png"))); // NOI18N
        salvarCartaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarCartaoButtonActionPerformed(evt);
            }
        });

        voltarCartaoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/iconeDeVoltarNew.png"))); // NOI18N
        voltarCartaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCartaoButtonActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Icon/iconeDeInforManagerNew2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salvarCartaoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarCartaoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(voltarCartaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarCartaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarCartaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCartaoButtonActionPerformed
        PosLogin pos = new PosLogin();
        pos.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_voltarCartaoButtonActionPerformed

    private void salvarCartaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarCartaoButtonActionPerformed
        String cartao = cartaoTextArea.getText().trim();

    if (cartao.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Digite um Numero de cartão!");
        return;
    }

    try {
        
        InfoDAO dao = new InfoDAO();
    dao.inserirCartao(cartao);

    FileWriter fw = new FileWriter("cartao.txt", true);
    fw.write(cartao + "\n");
    fw.close();

    JOptionPane.showMessageDialog(null, "Numero de cartão salvo com sucesso!");
    cartaoTextArea.setText("");
    
    }catch (Exception e) {
    JOptionPane.showMessageDialog(null,
            "Erro ao salvar:\n" + e.getMessage());
    }
    }//GEN-LAST:event_salvarCartaoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        FlatDarkLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cartao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cartaoTextArea;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salvarCartaoButton;
    private javax.swing.JButton voltarCartaoButton;
    // End of variables declaration//GEN-END:variables

private void carregarCartao() {
    try {
        InfoDAO dao = new InfoDAO();
        List<String> cartao = dao.listarCartao();

        cartaoTextArea.setText("");

        for (String ca : cartao) {
            cartaoTextArea.append(ca + "\n");
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}

}
