/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import com.formdev.flatlaf.FlatDarkLaf;
import java.io.FileWriter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ISAACOLIVEIRANUNES
 */
public class CPF extends javax.swing.JFrame {

    /**
     * Creates new form CPF
     */
    public CPF() {
        initComponents();

        setSize(493, 584);
        setTitle("CPF");
        setLocationRelativeTo(null);
        setResizable(false);

        salvarCpfButton.setContentAreaFilled(false); // Remove o preenchimento de fundo (cor cinza)
        salvarCpfButton.setBorderPainted(false);     // Remove a borda do botão
        salvarCpfButton.setFocusPainted(false);      // (Opcional) Remove a linha de foco ao clicar
        salvarCpfButton.setOpaque(false);

        voltarCpfButton.setContentAreaFilled(false); // Remove o preenchimento de fundo (cor cinza)
        voltarCpfButton.setBorderPainted(false);     // Remove a borda do botão
        voltarCpfButton.setFocusPainted(false);      // (Opcional) Remove a linha de foco ao clicar
        voltarCpfButton.setOpaque(false);

        jButton3.setContentAreaFilled(false); // Remove o preenchimento de fundo (cor cinza)
        jButton3.setBorderPainted(false);     // Remove a borda do botão
        jButton3.setFocusPainted(false);      // (Opcional) Remove a linha de foco ao clicar
        jButton3.setOpaque(false);
        
        cpfTextArea.setText("");
        carregarCpf();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cpfTextArea = new javax.swing.JTextArea();
        salvarCpfButton = new javax.swing.JButton();
        voltarCpfButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cpfTextArea.setColumns(20);
        cpfTextArea.setRows(5);
        jScrollPane1.setViewportView(cpfTextArea);

        salvarCpfButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/iconeDeSalvarNew.png"))); // NOI18N
        salvarCpfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarCpfButtonActionPerformed(evt);
            }
        });

        voltarCpfButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/iconeDeVoltarNew.png"))); // NOI18N
        voltarCpfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCpfButtonActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Icon/iconeDeInforManagerNew2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salvarCpfButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarCpfButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(voltarCpfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarCpfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarCpfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCpfButtonActionPerformed
        PosLogin pos = new PosLogin();
        pos.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarCpfButtonActionPerformed

    private void salvarCpfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarCpfButtonActionPerformed
      String cpf = cpfTextArea.getText().trim();

    if (cpf.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Digite um CPF!");
        return;
    }

    try {
        
        InfoDAO dao = new InfoDAO();
    dao.inserirCpf(cpf);

    FileWriter fw = new FileWriter("cpf.txt", true);
    fw.write(cpf + "\n");
    fw.close();

    JOptionPane.showMessageDialog(null, "CPF salvo com sucesso!");
    cpfTextArea.setText("");

} catch (Exception e) {
    JOptionPane.showMessageDialog(null,
            "Erro ao salvar:\n" + e.getMessage());
}
    }//GEN-LAST:event_salvarCpfButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
FlatDarkLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CPF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cpfTextArea;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salvarCpfButton;
    private javax.swing.JButton voltarCpfButton;
    // End of variables declaration//GEN-END:variables

 private void carregarCpf() {
    try {
        InfoDAO dao = new InfoDAO();
        List<String> cpf = dao.listarCpf();

        cpfTextArea.setText("");

        for (String cf : cpf) {
            cpfTextArea.append(cf + "\n");
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}

}
