/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ISAACOLIVEIRANUNES
 */
public class PosLogin extends javax.swing.JFrame {

    /**
     * Creates new form PosLogin
     */
    public PosLogin() {
        initComponents();
        setSize(493, 584);
        setTitle("APP");
        setLocationRelativeTo(null);
        setResizable(false);

        // DEIXAR O FUNDO DOS BOTÕES INVISIVEIS 
        senhaButton.setContentAreaFilled(false); // Remove o preenchimento de fundo (cor cinza)
        senhaButton.setBorderPainted(false);     // Remove a borda do botão
        senhaButton.setFocusPainted(false);      // (Opcional) Remove a linha de foco ao clicar
        senhaButton.setOpaque(false);

        cardSusButton.setContentAreaFilled(false); // Remove o preenchimento de fundo (cor cinza)
        cardSusButton.setBorderPainted(false);     // Remove a borda do botão
        cardSusButton.setFocusPainted(false);      // (Opcional) Remove a linha de foco ao clicar
        cardSusButton.setOpaque(false);

        emailButton.setContentAreaFilled(false); // Remove o preenchimento de fundo (cor cinza)
        emailButton.setBorderPainted(false);     // Remove a borda do botão
        emailButton.setFocusPainted(false);      // (Opcional) Remove a linha de foco ao clicar
        emailButton.setOpaque(false);

        cpfButton.setContentAreaFilled(false); // Remove o preenchimento de fundo (cor cinza)
        cpfButton.setBorderPainted(false);     // Remove a borda do botão
        cpfButton.setFocusPainted(false);      // (Opcional) Remove a linha de foco ao clicar
        cpfButton.setOpaque(false);

        sairButton.setContentAreaFilled(false); // Remove o preenchimento de fundo (cor cinza)
        sairButton.setBorderPainted(false);     // Remove a borda do botão
        sairButton.setFocusPainted(false);      // (Opcional) Remove a linha de foco ao clicar
        sairButton.setOpaque(false);

        cartaoButton.setContentAreaFilled(false); // Remove o preenchimento de fundo (cor cinza)
        cartaoButton.setBorderPainted(false);     // Remove a borda do botão
        cartaoButton.setFocusPainted(false);      // (Opcional) Remove a linha de foco ao clicar
        cartaoButton.setOpaque(false);

        // Configurando o JFrame
        setSize(493, 584);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(null);

        // Criando o JPanel com imagem de fundo
        JPanel P = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
            }
        };
        P.setBounds(50, 50, 493, 584); // Define posição e tamanho
        P.setOpaque(false); // Torna o painel transparente
        P.setLayout(null); // Define layout absoluto no painel

        // Adiciona o painel ao JFrame
        getContentPane().add(P);

        // Configurando o fundo
        ImageIcon imagemBackground = new ImageIcon("C:\\Users\\JOAOPEDROANTUNESDESO\\Desktop\\TelaDoAPP.png");
        JLabel labelBackground = new JLabel(imagemBackground);
        labelBackground.setBounds(0, 0, 493, 584);

        // Adiciona o fundo como último elemento
        getContentPane().add(labelBackground);
        setVisible(true);

        this.revalidate();
        this.repaint();
        setVisible(true);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        senhaButton = new javax.swing.JButton();
        emailButton = new javax.swing.JButton();
        cpfButton = new javax.swing.JButton();
        cardSusButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        cartaoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        senhaButton.setBackground(new java.awt.Color(204, 204, 204));
        senhaButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        senhaButton.setForeground(new java.awt.Color(255, 255, 255));
        senhaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Icon/iconeDeSenhaNew.png"))); // NOI18N
        senhaButton.setPreferredSize(new java.awt.Dimension(96, 77));
        senhaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaButtonActionPerformed(evt);
            }
        });

        emailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Icon/iconeDeEmailNovoNovo.png"))); // NOI18N
        emailButton.setPreferredSize(new java.awt.Dimension(96, 77));
        emailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailButtonActionPerformed(evt);
            }
        });

        cpfButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Icon/iconeDeCpfNew.png"))); // NOI18N
        cpfButton.setPreferredSize(new java.awt.Dimension(96, 77));
        cpfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfButtonActionPerformed(evt);
            }
        });

        cardSusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Icon/iconeDeCardSusNew.png"))); // NOI18N
        cardSusButton.setPreferredSize(new java.awt.Dimension(96, 77));
        cardSusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardSusButtonActionPerformed(evt);
            }
        });

        sairButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Icon/iconeDeSairNew.png"))); // NOI18N
        sairButton.setPreferredSize(new java.awt.Dimension(96, 77));
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        cartaoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Icon/iconeDeCardCreditoNew.png"))); // NOI18N
        cartaoButton.setPreferredSize(new java.awt.Dimension(96, 77));
        cartaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cartaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardSusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cartaoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardSusButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sairButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senhaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaButtonActionPerformed

        Senha senha = new Senha();
        senha.setVisible(true);
        dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_senhaButtonActionPerformed

    private void emailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailButtonActionPerformed
        Email email = new Email();
        email.setVisible(true);
        dispose();
    }//GEN-LAST:event_emailButtonActionPerformed

    private void cpfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfButtonActionPerformed
        CPF cpf = new CPF();
        cpf.setVisible(true);
        dispose();
    }//GEN-LAST:event_cpfButtonActionPerformed

    private void cartaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaoButtonActionPerformed
        Cartao card = new Cartao();
        card.setVisible(true);
        dispose();
    }//GEN-LAST:event_cartaoButtonActionPerformed

    private void cardSusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardSusButtonActionPerformed

        CardSus sus = new CardSus();
        sus.setVisible(true);
        dispose();
    }//GEN-LAST:event_cardSusButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        Loginn login = new Loginn();
        login.setVisible(true);
        dispose();

    }//GEN-LAST:event_sairButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PosLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PosLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PosLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PosLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PosLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cardSusButton;
    private javax.swing.JButton cartaoButton;
    private javax.swing.JButton cpfButton;
    private javax.swing.JButton emailButton;
    private javax.swing.JButton sairButton;
    private javax.swing.JButton senhaButton;
    // End of variables declaration//GEN-END:variables
}
